### PR TITLE
chore(benchmarks): upload benchmark results for environments

### PR DESCRIPTION
**Pull request by muchvo**
## Description

1. Upload benchmark results for environments.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Implemented Tasks

- [x] Subtask 1
- [x] Subtask 2
- [x] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/OmniSafeAI/safety-gymnasium/blob/main/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

### CODE REVIEW

**Comment by muchvo** [comment]
@liuzuxin Add benchmark results.

**Comment by muchvo** [comment]
> A nice Pull Request. The following suggestions may make it better:
> 
> * Add a link of Safety-Gym in your benchmark README file, like: [Safety Gym](https://openai.com/research/safety-gym)
> * Provide a `1e7` version of velocity benchmarks. Because the `SafetyHumanoidVelocity-v1` make little sense in `1e6` setting.

1. Solved.
2. 1e7 and 1e6 are both in this PR with the first commit.

**Review by Gaiejj — DISMISSED** [review]
LGTM.

**Review by Gaiejj — APPROVED** [review]
LGTM.

**Review by zmsn-2077 — APPROVED** [review]
LGTM.

**Pull request merged**
